version: "3.6"
services:
    postgres:
        image: postgres:latest
        ports:
            - 5151:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - dockernet
        environment:
            - POSTGRES_PASSWORD=A020197kc
            - POSTGRES_USER=postgres
            - POSTGRES_DB=sequelize
    redis:
        image: redis:latest
        ports:
            - 6161:6379
        networks:
            - dockernet
        depends_on:
            - postgres
    nodejs:
        image: atiakhairunican/jenkinsback:main
        ports:
            - 9001-9002:9000
        environment:
            - DBNAME=sequelize
            - DBPASSWORD=A020197kc
            - DBPORT=5432
            - DBHOST=localhost
            - DBUSER=postgres
            - JWT_KEYS = atiaKC
            - CLOUD_NAME = devopsatia
            - CLOUD_API_KEY = 343976629857324
            - CLOUD_API_SECRET = v-C70umdEJYOcwl8kdpkrfT-tq4
            - REDIS_HOST = localhost
            - REDIS_PORT = 6379
        networks:
            - dockernet
        depends_on:
            - postgres
        deploy:
            mode: replicated
            replicas: 2
            resources:
            limits:
                cpus: "0.50"
                memory: 50M
    vuejs:
        image: atiakhairunican/jenkinsfront:main
        ports:
            - 8181:8080
        environment:
            - VUE_APP_URL=http://localhost:9000/api/
networks:
    dockernet: